
DROP TABLE IF EXISTS  cokies;


CREATE TABLE cokies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ingridient TEXT NOT NULL,
    FOREIGN KEY (ingridient) REFERENCES Ingridient(name) ON DELETE RESTRICT

);
CREATE TABLE History (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    recipe TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  ,
    result INTEGER NOT NULL


);


CREATE TABLE Ingridient (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    cost INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    koef INTEGER NOT NULL
);
CREATE TABLE recipe (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    ingridients TEXT NOT NULL

);
